### ISSUE TITLE
Add example of extending the add-on's model in the dummy app.

### ISSUE THREAD

**Issue by sheriffderek** [oskarrough/ember-wordpress#10]
This may be a good opportunity to squash questions about adding featured images early, _like my first question._  ; )

**Comment by sheriffderek** [comment]
```
// custom model that extends the addon's 'post' model ~ "news" or something
// be sure to import DS (the Data Store) + import and extend the post model
import DS from 'ember-data';
import PostModel from "ember-wordpress/models/post";

export default PostModel.extend({
	better_featured_image: DS.attr(), // example property to add to the extended model
});
```

I didn't totally understand your first suggestions on this because I wasn't totally comfortable with _destructuring_ yet. I think it would be best to keep the docs with syntax that doesn't jump too far in the future for people who are new to Ember and ES6

**Comment by oskarrough** [comment]
Updated here: https://github.com/oskarrough/ember-wordpress#models
