### ISSUE TITLE
Only shows a max of 10 posts, even when wp-admin settings say otherwise

### ISSUE THREAD

**Issue by sheriffderek** [oskarrough/ember-wordpress#13]
Only shows a max of 10 posts, even when wp-admin settings say otherwise. That's only for 'posts' too, so where would we set the number of say, 'products' or 'projects' ? Any experience with that? Demo only has so much populated.

**Comment by oskarrough** [comment]
Yes, so 10 is the default limit from the WP-API. Changing it in the WP-ADMIN doesn't seem to affect it. This is the trick I use in my routes. 99 is the maximum number of posts that WP-API can deliver. If you need more, you need to use pagination.

```js
model() {
  return this.store.query('post', {per_page: 99});
}
```

I'll see to add this to the documentation and/or demo, thanks!

**Comment by sheriffderek** [comment]
Excellent. Thanks. I'm having a hard time understanding how the WP-api filter syntax works in general. Their documentation shows all of the parameters but not how to combine them. I'm likely overcomplicating it. https://github.com/WP-API/WP-API/issues/2457

Does this mean I can use load any combination of those keys into that object and things will just work?

```
model() {
  return this.store.query('post', {
    per_page: 99,
    key: value,
    key: value, // etc?
  });
}
```

**Comment by sheriffderek** [comment]
I just did some tests with those parameters and they work great. : ) I was putting them in the filter: {} before and it was just soft failing through.

```
	model() {
		let imagesData = this.store.query('image', {
			per_page: 99,
			categories: [4],
			tags: [5],
		});
		console.log(imagesData);
		return imagesData;
	}
```

**Comment by sheriffderek** [comment]
If we add a note about the limitation and an example of the implementation - then this would be unlikely to be asked about again - and can be closed out.  : )

**Comment by oskarrough** [comment]
Hey, I updated the readme now. How does it look to you?

https://github.com/oskarrough/ember-wordpress#queries
