### ISSUE TITLE
deploy on github pages

### ISSUE THREAD

**Issue by a-s-f** [oskarrough/ember-wordpress#19]
hey I can't seem to get this going for github pages, only surge, has anyone had any luck with it on github pages or can someone push me in the right direction?

**Comment by sheriffderek** [comment]
Do you mean you want to put an Ember application on github pages? Or you have it setup with github pages, but the data isn't coming through from WordPress? Or you've cloned the app and want to make a demo page from the dummy app? Maybe something here can help ? https://github.com/poetic/ember-cli-github-pages

**Comment by a-s-f** [comment]
I think I am running into a problem with the deploy script?
would this
 `    "deploy": "ember github-pages:commit --message \"Deploy gh-pages from commit $(git rev-parse HEAD)\"; git push; git checkout -"
`
just replace

`    "deploy": "npm run build; mv dist/index.html dist/200.html; surge dist ember-wordpress.surge.sh"`
