### ISSUE TITLE
ACF now has a API Plugin

### ISSUE THREAD

**Issue by drewcovi** [oskarrough/ember-wordpress#21]
Caught this in a few threads, as you recommend ACF might also recommend: https://wordpress.org/plugins/acf-to-wp-api/

**Comment by oskarrough** [comment]
Thank you. But I've actually been using https://github.com/airesvsg/acf-to-rest-api (from the readme) instead. Since the two seem so similar I thought it better to only link the most up to date one.

**Comment by drewcovi** [comment]
Weird, somehow I grabbed everything else but missed that. Never mind :)

**Comment by drewcovi** [comment]
Turns out they're basically identical (didnt even need to touch my client code), but the one you have linked up (v2) documents more than just GET requests.  Thanks!!!
