### ISSUE TITLE
What is the fastboot 'story' so far?

### ISSUE THREAD

**Issue by sheriffderek** [oskarrough/ember-wordpress#26]
What is the fastboot 'story' so far?

Has anyone worked with it in this scenario? I'm going to try it out and see what happens, but it would be nice to have a section in the readme so people know what to expect.

**Comment by oskarrough** [comment]
I tested it some months ago and it works well, actually. I didn't get around to figure out where to host it, so the version online at https://ember-wordpress.surge.sh isn't with fastboot.

Please see https://github.com/oskarrough/ember-wordpress/tree/fastboot

**Comment by oskarrough** [comment]
You can see it working here: https://ember-wordpress-nymqnnqwxp.now.sh/posts/ember-wordpress-works (check the source)

https://github.com/oskarrough/ember-wordpress/pull/27

**Comment by sheriffderek** [comment]
Excellent.
