### ISSUE TITLE
Documentation and demo app not compatible with WP REST API v2.0

### ISSUE THREAD

**Issue by hakilebara** [oskarrough/ember-wordpress#29]
In WP REST API v2.0 (which has been merged into Wordpress core 4.7 and Wordpress.com) filters were removed. 
The way to query by slug or by category has changed. (cf. https://github.com/WP-API/WP-API#about)

Query by slug:
`GET /wp-json/wp/v2/posts?slug=some-post-slug`

Query by category (requires now two requests)
`/wp/v2/categories?slug=some-category-slug` (to get the category id)
`/wp/v2/posts?categories=some-category-id`

**Comment by oskarrough** [comment]
Ah, that's nice. Thanks for letting me know. I'll update unless you want to give it a go?

**Comment by hakilebara** [comment]
Sure, I'll create a PR once I get back home :)

**Comment by hakilebara** [comment]
#30

**Comment by hakilebara** [comment]
PR submitted #30

**Comment by oskarrough** [comment]
Closed thanks to @hakilebara!
