### ISSUE TITLE
Document how to query, work with categories and tags etc.

### ISSUE THREAD

**Issue by oskarrough** [oskarrough/ember-wordpress#3]
Categories and tag relationships work. You can also query by them, or by custom fields. But additional work and tricks are required. It should be documented.

**Comment by OMAKevin** [comment]
Please... do document

**Comment by oskarrough** [comment]
Any certain areas I could focus on?

**Comment by sheriffderek** [comment]
What about just a few complex example. A post, with a Category, a post with a tag, , with a cat but only when it has 2 particular tags etc.

Maybe have examples of how to find the records in an outer route, and then peek them in sub routes to keep down requests.

I imagine people, when they see WordPress - people are going to expect pagination and WP type stuff.

**Comment by sheriffderek** [comment]
I have been playing with a branch here: https://github.com/sheriffderek/ember-wordpress/tree/category-exploration - to try and get to the bottom of the things that still confuse me. Mainly filtering resources.

**Comment by sheriffderek** [comment]
New readme looking good!

**Comment by oskarrough** [comment]
I just updated the demo app (in dummy/tests) so you can see and browse posts by category. That should hopefully explain it. Otherwise please reopen.
