### ISSUE TITLE
DEMO: Posts not changing

### ISSUE THREAD

**Issue by codeclinic** [oskarrough/ember-wordpress#32]
This may simply be an issue with the demo site....

When viewing the posts (on the demo site) the first post shows as expected. However, clicking to view a different post results in the url changing to the relevant url but the page content remains the same. Regardless of which page is selected, or the journey taken to reach the available posts, only the 'parrot' page is ever shown.

**Comment by hakilebara** [comment]
This issue has been fixed in #30 
@oskarrough has the fix been deployed to surge.sh ?

**Comment by oskarrough** [comment]
Must have forgotten… It's deployed now and seems to works again. Thanks for reporting!
