### ISSUE TITLE
Demo is currently broken

### ISSUE THREAD

**Issue by sheriffderek** [oskarrough/ember-wordpress#36]
Subject

**Comment by oskarrough** [comment]
Thanks! Should work again now.

Pantheon, where I host the Wordpress install, has begun "freezing" free accounts. I'll have to login every three months to avoid it.. If anyone knows another free Wordpress host, I'm open for suggestions :)

https://pantheon.io/docs/platform-considerations/#inactive-site-freezing.

**Comment by robwebdev** [comment]
@oskarrough Pantheon appears to have frozen the account again and the demo is currently broken.

**Comment by oskarrough** [comment]
@robwebdev thanks. Unfrozen again ;)
