### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by kedano** [oskarrough/ember-wordpress#4]
Is it possible to plug this into an ember app out of the box? Could you please create a sample project?

**Comment by oskarrough** [comment]
Hey, no not out of the box. What you need to do is use the serializer and adapter from this repo as well as a model class that matches whatever properties you intend to use from the Wordpress API.

A sample project would definitely help here. I'll try to find time soon! Until then, if you have any questions, please ask.

**Comment by oskarrough** [comment]
I believe it's working now, out of the box. I published v0.1.0. See the updated readme and the tests/dummy folder for inspiration.
