### ISSUE TITLE
Wrong/cached model loading despite changing route

### ISSUE THREAD

**Issue by gregorymark** [oskarrough/ember-wordpress#42]
Awesome work on this addon, it's made my life much easier!

I was having a real issue working out why Ember was caching my first loaded model, despite changing routes in my build. It seems that because I was not defining models in my app (as in the demo) but relying on the addon defined models, the models were all being initially cached as having the same model type. Therefore subsequent calls to the API were building the same URL from the same model name, though with the correct parameters. The result was that it was returning e.g. pages when I wanted posts if the first route loaded was a page and the second to posts.

Adding models in my app as simply as
```
import Post from 'ember-wordpress/models/post';

export default Post.extend({
});
```
solved the problem, though using
```
export { default } from 'ember-wordpress/models/post';
```
everywhere didn't.

I'm pretty new to Ember so it's possible I'm making a rookie error here or elsewhere (though I built a minimal use-case as close to the demo as I could get and was still having the same issue), but I noticed that the demo build uses a pretty old version of Ember - is that behaviour that's changed? Is it worth updating the demo build? It certainly took me a while to track down!

For the record this is how I'm loading my /about route
```
import Route from '@ember/routing/route';

export default Route.extend({
    model() {
        return this.store.query('page', {slug: 'about'}).then(models => models.get('firstObject'));
    }
});
```

Anyway, working now, mostly to save time for anyone else who's having this issue, unless it's worth updating the demo environment if I'm correct.

**Comment by oskarrough** [comment]
Almost doesn't sound like it made it easier hehe.  But thank you!

You might have found something here. The addon gives you a `post` as well as a `page` model. Behind the scenes these two both extend from the same [addon/models/post.js](https://github.com/oskarrough/ember-wordpress/blob/master/addon/models/post.js).

Can you reproduce it in the demo app?

**Comment by gregorymark** [comment]
Hehe, I'd definitely still be working things out if I didn't have the addon!

So when you say reproduce it from the demo app I've tried installing [this](https://github.com/oskarrough/ember-wordpress/tree/master/tests/dummy) as my app, but I can't seem to get past a load of errors (not finding files and so on). Is that what you mean?

**Comment by oskarrough** [comment]
Almost. If you `git clone` this repository and run `ember serve` it'll serve the "dummy app" (same as you linked).

I thought if you can reproduce the error there as well it would be easier to track it down :)

**Comment by gregorymark** [comment]
Right, yes. Easier than I thought :)

It's having the same problem there. Categories load because they're using a different model, but requests using the same model use the first model name requested.

If I change the models defined in `app/models` as follows
```
import Post from 'ember-wordpress/models/post';

export default Post.extend({
});
```
then it works and requests the correct URL.

**Comment by oskarrough** [comment]
@gregorymark mind verifying that it works here? https://github.com/oskarrough/ember-wordpress/pull/44. Then I can merge and release a new version.

**Comment by gregorymark** [comment]
@oskarrough yep that's working.
