### ISSUE TITLE
Website is Broken

### ISSUE THREAD

**Issue by ballPointPenguin** [oskarrough/ember-wordpress#46]
https://ember-wordpress.surge.sh/ is not fully loading in Firefox or Chrome for me.
It looks like a cross-site-origin issue, maybe. I have not investigated further.

**Comment by oskarrough** [comment]
Thanks, I'll get it up again.

It happens once in a while because I'm using a free Pantheon account (the wordpress backend)…… https://github.com/oskarrough/ember-wordpress/issues/36#issuecomment-314861943

**Comment by ballPointPenguin** [comment]
Looks good now :+1:
