### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by kedano** [oskarrough/ember-wordpress#5]
Thanks a lot for the update. I created a new ember 2.3 app, followed the updated install instructions of this plugin. 

I generated page and post resourses with `ember g resource post` and `ember g resource page`. After implementing the views I had to add the data-fields on each resource `model/*.js`  file. Is there a way to inject the models defined in the addon out of the box or should there be some more information regarding this in the readme?

**Comment by oskarrough** [comment]
The models should be there, no need to generate them. If you do however create them yourself, you have to make sure they extend the default ones.

See here for examples: https://github.com/oskarrough/ember-wordpress/tree/master/app/models

Let me know if it works :)

**Comment by kedano** [comment]
Yea, my bad. The `ember g resource post` generate empty model files that overwrite the standard definitions from the plugin.

**Comment by oskarrough** [comment]
I'm sure this will pop up again unless it's mentioned in the readme. Thank you for noting it, I'll update it.

**Comment by oskarrough** [comment]
Added a small note to the readme now.
