### ISSUE TITLE
Environment  emberWordpress documentation not working.

### ISSUE THREAD

**Issue by rashid301** [oskarrough/ember-wordpress#51]
I installed the latest release v0.2.0. 
The documented configuration did not work. 

> // config/environment.js
> ...
> ENV.emberWordpress: {
>    host: 'https://my-wordpress-site.com'
> }

After looking at code, I changed it to

> ENV.wordpressHost: 'https://my-wordpress-site.com'

This worked for me.

**Comment by oskarrough** [comment]
Hey thanks for reporting. You're right..  it was supposed to be part of 2.0.0 but I messed up the releases. I'll add it to the docs. I just verified:

- 2.0.0 and below uses `ENV.wordpressHost`
- From 2.0.1 and forwards it should be `ENV.emberWordpress.host`

**Comment by oskarrough** [comment]
https://github.com/oskarrough/ember-wordpress/commit/3d973568446a653c8f6753bf3affc7fa45eef725
