### ISSUE TITLE
Custom post type returns 404

### ISSUE THREAD

**Issue by rizkysyazuli** [oskarrough/ember-wordpress#54]
I'm trying to fetch an "Experience" custom post for my portfolio site. But i'm getting a 404 because the request goes to Ember's `/experiences` instead of WP's `/wp-json/wp/v2/experiences`.

I've set the `rest_base` to be `experiences` and using these Ember configs:

```js
// app/models/experience.js
import DS from 'ember-data';
import PostModel from 'ember-wordpress/models/post';

export default PostModel.extend({
  experiences: DS.attr()
});
```

The model itself is being called from the index page.

```js
// app/routes/index.js
import Route from '@ember/routing/route';
import RSVP from 'rsvp';

export default Route.extend({
  model() {
    return RSVP.hash({
      experiences: this.store.findAll('experience'),
      ...
    })
  }
});
```

I'm using Ember 3.14.0 and Ember WordPress 0.2.2
What am I missing here?

**Comment by oskarrough** [comment]
The endpoint URL is based on the `host` and `namespace` values here https://github.com/oskarrough/ember-wordpress/blob/master/addon/adapters/wordpress.js.

As it's not using those in your example, maybe the addon isn't installed properly? Try `ember install ember-wordpress` again.

**Comment by rizkysyazuli** [comment]
hmm.. nope. still not working.  and here, i forgot to include my environment.js file.

```js
module.exports = function(environment) {
  let ENV = {
    ...

    emberWordpress: {
      host: 'http://my.site/wordpress'
    }
  };

  if (environment === 'development') {
    // local wordpress docker container
    ENV.emberWordpress.host = 'http://localhost:8080';
  }

  return ENV;
};
```

FYI, i'm currently working in a Docker environment, if that matters.

**Comment by oskarrough** [comment]
Hm, looks correct to me. It's the same we do here https://github.com/oskarrough/ember-wordpress/blob/master/tests/dummy/config/environment.js#L26-L28.

**Comment by rizkysyazuli** [comment]
anyway, i looked into my last project that uses `ember-wordpress`. it uses version 0.1.8. so, i switched to this version. aaaand.. the error is gone.

this problem with custom post types seems to happen starting from version 0.2.0. so u might want to take a look at this.

i'm reverting to 0.1.8 for now.
