### ISSUE TITLE
A path for working with featured-images

### ISSUE THREAD

**Issue by sheriffderek** [oskarrough/ember-wordpress#6]
I threw together a quick 4 page site to try out your new add-on. It's great! I look forward to digging in a bit deeper.

I see a "featured_media": N, but do you have any plans to involve a more in-depth use of featured images? I've just tried using [Better REST API Featured Images](https://wordpress.org/plugins/better-rest-api-featured-images/) on a recent project. That could be something of interest.

I just added `better_featured_image: attr()` to the bottom of the post model and BAM. That works wonderfully. I imagine I should properly extend that. : )

Any help on the syntax for extending the model? This is what I've tried in `app/models/post.js`

```
import post from 'ember-wordpress/models/post';

export default post.extend({
	better_featured_image: attr()
});
```

**Comment by oskarrough** [comment]
Good to hear it's working!

We've been using exactly that project and extending the model as you describe. It works just fine. But what works even better, I think, is using Advanced Custom Fields and its image field. The JSON output is easier to work with. But without ACF, I'd go with that you suggested.

I think this project deserves an extensive guide. Perhaps I should add a section about how to handle media/images to the readme?

**Comment by sheriffderek** [comment]
I think a guide would be great. I've been struggling with this for a while, and it's because I don't understand how the payload works and how it changes and how to best reformat to jsonapi. Your efforts are a great help to me. I'll keep track of things and help you suss out the best way to explain.

I much prefer ACF, and don't love writing `better_featured_images.thing` / however I leverage the PHP magic to build out many different sized files and then serve them according to screen-size and bandwidth etc.. I'm pretty sure that I can use ACF like the regular featured image and get those benefits but I haven't tried.

A good thing for the guide would be how to hook up images, and also how to deal with a custom post type.

PS my attempt to extend the model did not seem to pan out. Does that code look right?

**Comment by oskarrough** [comment]
You need to define where `attr` comes from. Otherwise it looks correct to me.

```javascript
import PostModel from 'ember-wordpress/models/post';
import DS from 'ember-data';

export default PostModel.extend({
    better_featured_image: DS.attr()
});
```

But great with your help! Feel free to open any questions/issues here and I'll attempt to answer them and collect them into the readme.

**Comment by sheriffderek** [comment]
Ah Ha! I was also shortening that DS. with a variable - and forgot

**Comment by sheriffderek** [comment]
I kept wondering what you meant. "...But what works even better, I think, is using Advanced Custom Fields and its image field." Turns out I was so used to clicking 
<img width="532" alt="screen shot 2016-04-06 at 5 35 33 pm" src="https://cloud.githubusercontent.com/assets/2066617/14336959/08eb380e-fc1e-11e5-85ca-e134d166e10c.png">
that I forgot about using image array. I'm so glad you made me check back in on this. ACF has everything that the featured image was doing for me and I didn't even know it. Very happy about this. : )

**Comment by oskarrough** [comment]
Aah, great! Yes. Also, ACF can enforce min/max values for image sizes which makes it easier to ensure clients upload proper images.

**Comment by josephbergdoll** [comment]
Would love a section on how to handle images in readme.
