### ISSUE TITLE
`Error: 'content' is a reserved property name on instances of classes extending Model. Please choose a different property name for model:wordpress/post`

### ISSUE THREAD

**Issue by charlesfries** [oskarrough/ember-wordpress#60]
`Error: 'content' is a reserved property name on instances of classes extending Model. Please choose a different property name for model:wordpress/post`

It seems `content` is an invalid attribute name in v3.28.

```
ember-cli: 3.28.0
node: 14.17.1
os: win32 x64
```

**Comment by oskarrough** [comment]
Since the property IS called `content` in the Wordpress API it feels bad to rename it in the serializer/adapter? but I guess that's the only way. What other options do we have?

**Comment by charlesfries** [comment]
Sorry for the late reply. Should be super easy, we just need to override the `PostSerializer` and remap the key. We can expect `content` as the key in the JSON server response, but we can map it to something like `body` or `_content` in Ember Data.

```javascript
import WordpressSerializer from './wordpress';

export default class PostSerializer extends WordpressSerializer {
  attrs = {
    _content: 'content'
  };
}
```

**Comment by charlesfries** [comment]
I think the Ember team decided against this change. Closing
