### ISSUE TITLE
Think about adopting an official code-style or combination

### ISSUE THREAD

**Issue by sheriffderek** [oskarrough/ember-wordpress#8]
Is there currently any official code-style or combination thereof? I only mention it, because if you are - it's easiest to do early on. : )

[Ember style guide](https://github.com/emberjs/ember.js/blob/master/STYLEGUIDE.md)
[JavaScript code style](http://jscs.info/)
[Ember-suave](https://github.com/DockYard/ember-suave)

**Comment by oskarrough** [comment]
Sure! The project follows https://github.com/sindresorhus/xo as I, personally, prefer using something not related to Ember. That being said https://github.com/DockYard/styleguides/blob/master/engineering/ember.md is very well thought.

I've added a note https://github.com/oskarrough/ember-wordpress/commit/9f5084fce9e7bd59c8b9661cb4236053c58536b3.
