### ISSUE TITLE
Add an example of how to incorporate a custom post type

### ISSUE THREAD

**Issue by sheriffderek** [oskarrough/ember-wordpress#9]
Maybe in the dummy app there can be one custom post type to show how that may work. "Projects" or "Products" or something.

**Comment by oskarrough** [comment]
Good idea. The important parts are the two options `show_in_rest`, which must be set to true and `rest_base` which will be the endpoint of your post type. Be sure to set this to plural, as this is what Ember expects.

https://github.com/oskarrough/ember-wordpress/blob/master/README.md#wordpress-custom-post-types
